// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbj3lg5FD9ytk8t6p2vqEm9EodjNtjM5E',
    appId: '1:638778848216:web:df92abd09add82909d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    authDomain: 'bip-projects.firebaseapp.com',
    storageBucket: 'bip-projects.appspot.com',
    measurementId: 'G-2HL2VD67LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpdpVYDvt0nXKoRIRZN6oQW8s-KHPBfmk',
    appId: '1:638778848216:android:70e4b78c090b4b5d9d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    storageBucket: 'bip-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAljS83XEl8Sh19n4ohOZlD-VVdBx5yr-8',
    appId: '1:638778848216:ios:a87dda5846554d9c9d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    storageBucket: 'bip-projects.appspot.com',
    iosClientId: '638778848216-v3idtc2g00scbbt46jd74b8rvq533hhm.apps.googleusercontent.com',
    iosBundleId: 'com.tasktimetracker.taskTimeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAljS83XEl8Sh19n4ohOZlD-VVdBx5yr-8',
    appId: '1:638778848216:ios:fa0719878841c7389d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    storageBucket: 'bip-projects.appspot.com',
    iosClientId: '638778848216-0vamjopuhhqifici6l9jeb5470kdbuii.apps.googleusercontent.com',
    iosBundleId: 'com.tasktimetracker.taskTimeTracker.RunnerTests',
  );
}
